import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faTwitter, faDiscord, faGithub } from '@fortawesome/free-brands-svg-icons'
import { faCirclePlay } from '@fortawesome/free-regular-svg-icons'
import { faChevronDown } from '@fortawesome/free-solid-svg-icons'

const s = {
  link: 'text-sm',
}

export default function Home() {
  return (
    <div className="bg-black text-white">
      <Head>
        <title>CodeEdit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="w-full flex justify-between p-5 border-b border-white/10 fixed top-0 left-0 right-0 z-10 bg-black/80 backdrop-blur-md backdrop-saturate-150">
        <a href="#" className="w-2/12 flex items-center">
          <Image src="/codeedit-logo.png" alt="CodeEdit Logo" width={128} height={21} />
        </a>

        <nav className="hidden md:flex self-center space-x-6">
          <a href="#" className={s.link}>
            Extensions
          </a>
          <a href="#" className={s.link}>
            Documentation
          </a>
          <a href="#" className={s.link}>
            Changelog
          </a>
          <a href="#" className={s.link}>
            Blog
          </a>
          <a href="#" className={s.link}>
            FAQ
          </a>
          <a href="#" className={s.link}>
            About
          </a>
        </nav>

        <nav className="flex space-x-4 items-center justify-end w-2/12">
          <a href="#">
            <FontAwesomeIcon icon={faTwitter} className="w-5" />
          </a>
          <a href="#">
            <FontAwesomeIcon icon={faDiscord} className="w-5" />
          </a>
          <a href="#">
            <FontAwesomeIcon icon={faGithub} className="w-5" />
          </a>
        </nav>
      </header>

      <main className={`${styles.main} pt-16`}>
        <section className="relative min-h-full w-full bg-gradient bg-[center_bottom_-16rem] sm:bg-[center_bottom_-20rem] md:bg-[center_bottom_-25rem] lg:bg-[center_bottom_-25rem] bg-no-repeat bg-135% lg:bg-115% flex flex-col items-center">
          <div className="mt-16">
            <Image src="/codeedit-icon.png" alt="CodeEdit Icon" width={100} height={100} />
          </div>

          <h1 className="text-2xl md:text-3xl lg:text-5xl font-semibold mt-3">Elevate your editing experience.</h1>

          <p className="text-white/50 font-light text-xl lg:text-xl mt-6">Open source, free forever.</p>

          <a href="#" className="bg-blue-500 py-2 px-4 rounded-3xl mt-10 flex">
            <span>Download</span>
            <FontAwesomeIcon icon={faChevronDown} className="ml-2 w-3" />
          </a>

          <div className="mt-6 text-white/50 flex divide-x divide-white/20 text-sm leading-none">
            <span className="px-3">v1.31.0</span>
            <span className="px-3">macOS 12.0+</span>
            <span className="px-3">Install via Homebrew</span>
          </div>

          <div className="mt-10 flex mb-5">
            <span className="text-xl">Watch the film</span>
            <FontAwesomeIcon icon={faCirclePlay} className="ml-2 w-6" />
          </div>

          <img src="/codeedit-screen-transparent.png" className="w-5/6"></img>

          <div className="absolute bg-gradient-to-t from-black w-full bottom-16 lg:bottom-32 h-16 lg:h-32"></div>
          <div className="absolute bg-black w-full bottom-0 h-16 lg:h-32"></div>
        </section>
      </main>
    </div>
  )
}
