import {useState, useEffect} from "react";
import Head from "next/head";
import Image from "next/image";
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
import {
    faTwitter,
    faDiscord,
    faGithub
} from "@fortawesome/free-brands-svg-icons";
import {
    faCirclePlay,
    faSun,
    faMoon
} from "@fortawesome/free-regular-svg-icons";
import {faChevronDown} from "@fortawesome/free-solid-svg-icons";
import AOS from 'aos';
import 'aos/dist/aos.css';

import { Typewriter } from 'react-simple-typewriter';

const useDeviceMode = () => {
    const [darkMode, setDarkMode] = useState(false);
    useEffect(() => {
        setDarkMode(
            window.matchMedia &&
            window.matchMedia("(prefers-color-scheme: dark)").matches
        );
        const modeMe = (e) => {
            setDarkMode(!!e.matches);
        };
        window
            .matchMedia("(prefers-color-scheme: dark)")
            .addEventListener("change", modeMe);
        return window
            .matchMedia("(prefers-color-scheme: dark)")
            .removeListener(modeMe);
    }, []);
    return [darkMode, setDarkMode];
};

export default function Home() {
    const [darkMode, setDarkMode] = useDeviceMode();
    const type = darkMode ? "dark" : "light";
    const bg = darkMode ? "bg-black" : "bg-white";
    const text = darkMode ? "text-white" : "text-black";

    useEffect(() => {
        AOS.init({duration: 2000});
    }, []);


    return (
        <div className={`${bg} ${text}`}>
            <Head>
                <title>CodeEdit</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href={`favicon-light.ico`}/>
            </Head>

            <header className="w-full flex justify-between p-5 border-b border-gray-800">
                <a href="#">
                    <Image
                        src={`/codeedit-logo-${type}.png`}
                        alt="CodeEdit Logo"
                        width={128}
                        height={21}
                    />
                </a>

                <nav className="hidden md:block self-center flex space-x-4">
                    <a href="#">Extensions</a>
                    <a href="#">Documentation</a>
                    <a href="#">Changelog</a>
                    <a href="#">Blog</a>
                    <a href="#">FAQ</a>
                    <a href="#">About</a>
                </nav>

                <nav className="flex space-x-3 items-center">
                    <a href="#">
                        <FontAwesomeIcon icon={faTwitter} className="w-5"/>
                    </a>
                    <a href="#">
                        <FontAwesomeIcon icon={faDiscord} className="w-5"/>
                    </a>
                    <a href="#">
                        <FontAwesomeIcon icon={faGithub} className="w-5"/>
                    </a>
                    <a href="#">
                        <FontAwesomeIcon
                            icon={darkMode ? faSun : faMoon}
                            className="ml-2 w-6"
                            onClick={() => setDarkMode((prev) => !prev)}
                        />
                    </a>
                </nav>
            </header>

            <main>

                <section
                    className={`relative min-h-full w-full ${bg} bg-[center_bottom_-16rem] sm:bg-[center_bottom_-20rem] md:bg-[center_bottom_-25rem] lg:bg-[center_bottom_-25rem] bg-no-repeat bg-135% lg:bg-115% flex flex-col items-center`}
                >
                    <div className="mt-16">
                        <Image
                            src="/codeedit-icon.png"
                            alt="CodeEdit Icon"
                            width={100}
                            height={100}
                        />
                    </div>

                    <div className="rd-gradient"/>
                    <h1 className="text-2xl md:text-3xl lg:text-5xl font-semibold mt-3">
                        Elevate your editing experience.
                    </h1>

                    <p className="text-gray-400 font-light text-xl lg:text-2xl mt-4">
                        <Typewriter
                            words={['Open source, free forever.']}
                            typeSpeed={70}
                            deleteSpeed={50}
                            delaySpeed={10000}
                        />
                    </p>
                    <a
                        href="#"
                        className="bg-blue-500 py-2 px-4 rounded-3xl mt-10 flex"
                    >
                        <span>Download</span>
                        <FontAwesomeIcon icon={faChevronDown} className="ml-2 w-3"/>
                    </a>

                    <div className="mt-6 text-gray-400 flex divide-x divide-gray-400 text-sm">
                        <span className="px-3">v1.0.0</span>
                        <span className="px-3">macOS 12.0+</span>
                        <span className="px-3">Install via Homebrew</span>
                    </div>

                    <div className="mt-10 flex mb-5">
                        <span className="text-xl lg:text-2xl">Watch the film</span>
                        <FontAwesomeIcon icon={faCirclePlay} className="ml-2 w-6"/>
                    </div>
                    <img
                        src={`/codeedit-screen-${type}.png`}
                        className="w-5/6 screen"
                        alt={"Screen"}
                    />
                    <div
                        className={`absolute bg-gradient-to-t ${
                            darkMode ? "from-black" : "from-white"
                        } w-full bottom-16 lg:bottom-32 h-16 lg:h-32`}
                    />
                    <div
                        className={`absolute ${bg} w-full bottom-0 h-16 lg:h-32`}
                    />
                </section>

                <section
                    className={`text-center-webkit-left relative min-h-full w-full ${bg} bg-[center_bottom_-16rem] sm:bg-[center_bottom_-20rem] md:bg-[center_bottom_-25rem] lg:bg-[center_bottom_-25rem] bg-no-repeat bg-135% lg:bg-115% flex flex-col items-center`}
                >
                    <div className="inline-flex" data-aos="fade-right">
                        <img
                            src={`/codeedit-screen-split.png`}
                            className="w-3/6"
                            alt={"Screen"}
                        />
                        <div className="text-gray-400 font-light text-xl lg:text-2xl mt-4 flex-auto">
                            Elevate your editing experience.
                        </div>
                    </div>
                </section>

                <section
                    className={`text-center-webkit-right relative min-h-full w-full ${bg} bg-[center_bottom_-16rem] sm:bg-[center_bottom_-20rem] md:bg-[center_bottom_-25rem] lg:bg-[center_bottom_-25rem] bg-no-repeat bg-135% lg:bg-115% flex flex-col items-center`}
                >
                    <div className="inline-flex" data-aos="fade-left">
                        <div className="text-gray-400 font-light text-xl lg:text-2xl mt-4 flex-auto">
                            Elevate your editing experience.
                        </div>
                        <img
                            src={`/codeedit-screen-find.png`}
                            className="w-3/6"
                            alt={"Screen"}
                        />
                    </div>
                </section>

            </main>
        </div>
    );
}
